name: RetrosLodestones
version: ${project.version}
main: com.gitlab.retropronghorn.retroslodestones.RetrosLodestones
api-version: 1.13
authors: [RetroPronghorn]
description: Retro's Lodestones adds teleport functionality to lodestones in Minecraft 1.16+ Players can bind a compass to a lodestone then right click the compass on a respawn anchor, consuming a single glowstone charge, to teleport to the bound lodestone.
website: https://gitlab.com/RetroPronghorn/retros-lodestones
commands:
  retroslodestones:
    description: Plugin info
permissions:
  retroslodestones.use:
    description: Allows a user to access the core functionality of the plugin
    default: op
